name: Push-Luna-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: "/home/ubuntu/luna"
          SOURCE: "."

      - name: Excecuting remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            sudo apt-get -y update
            sudo apt-get -y install nodejs
            cd /home/ubuntu/luna
            sudo move * .[^.]* /home/ubuntu/luna
            npm install
            npm run start
            pm2 restart all

      - name: create env file
        run: |
          cd /home/ubuntu/luna
          touch .env
          echo PORT=${{ secrets.PORT }} >> .env
          echo MONGO_URI=${{ secrets.MONGO_URI }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
