name: Push-Luna-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: "/home/ubuntu/luna"
          SOURCE: "."

      - name: ssh
        image: appleboy/drone-ssh
        uses: easingthemes/ssh-deploy@main
        settings:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script:
            - cd /home/ubuntu/luna
            - sudo move * .[^.]* /home/ubuntu/luna
            - npm install
            - touch .env
            - echo PORT=${{ secrets.PORT }} >> .env
            - echo MONGO_URI=${{ secrets.MONGO_URI }} >> .env
            - echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
            - npm start
